# Generated by Django 5.1.4 on 2026-03-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="模型名称"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="模型描述")),
                ("schema", models.JSONField(default=dict, verbose_name="模型 Schema")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "数据模型",
                "verbose_name_plural": "数据模型",
                "db_table": "data_model",
                "ordering": ["-created_at"],
            },
        ),
    ]
