# Generated by Django 5.1.4 on 2026-03-18 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(default=dict, verbose_name="表单数据")),
                (
                    "submitted_by",
                    models.CharField(blank=True, max_length=100, verbose_name="提交人"),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_data",
                        to="core.datamodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "表单数据",
                "verbose_name_plural": "表单数据",
                "db_table": "form_data",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
