# Generated by Django 5.1.4 on 2026-03-18 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_formdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="布局名称")),
                ("layout", models.JSONField(default=dict, verbose_name="布局配置")),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="是否生效"),
                ),
                ("version", models.IntegerField(default=1, verbose_name="版本号")),
                (
                    "created_by",
                    models.CharField(blank=True, max_length=100, verbose_name="创建人"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layouts",
                        to="core.datamodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "表单布局",
                "verbose_name_plural": "表单布局",
                "db_table": "form_layout",
                "ordering": ["-updated_at"],
                "unique_together": {("model", "name")},
            },
        ),
    ]
